In [1]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv('../datasources/example_tennis.csv')

from sklearn import preprocessing
data2 = data.apply(preprocessing.LabelEncoder().fit_transform)

columnHeadings = data2.iloc[:,:1]

from sklearn import preprocessing
oneHotEncoder = preprocessing.OneHotEncoder()
columnHeadings=oneHotEncoder.fit_transform(columnHeadings).toarray()
print(columnHeadings)

Outlook = pd.DataFrame(data=columnHeadings, index = range(14), columns=['Overcast','Rainy','Sunny'])
lastdata = pd.concat([Outlook,data.iloc[:,1:3]],axis=1)
lastdata = pd.concat([data2.iloc[:,-2:],lastdata],axis=1)



from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(lastdata.iloc[:,:-1],lastdata.iloc[:,-1:],test_size=0.33, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)


y_prediction = regressor.predict(x_test)

print(y_prediction)

import statsmodels.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=lastdata.iloc[:,:-1], axis=1 )
X_l = lastdata.iloc[:,[0,1,2,3,4,5]].values
X_l=np.array(X_l,dtype=float)
model = sm.OLS(lastdata.iloc[:,-1:],X_l).fit()
print(model.summary())

lastdata = lastdata.iloc[:,1:]

#Backward Elimination
import statsmodels.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=lastdata.iloc[:,:-1], axis=1 )
X_l = lastdata.iloc[:,[0,1,2,3,4]].values
X_l=np.array(X_l,dtype=float)
model = sm.OLS(lastdata.iloc[:,-1:],X_l).fit()
print(model.summary())


x_train = x_train.iloc[:,1:]
x_test = x_test.iloc[:,1:]

regressor.fit(x_train,y_train)


y_prediction = regressor.predict(x_test)



[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[84.45365573]
 [63.93839954]
 [85.76050662]
 [64.21013241]
 [75.06793322]]
                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Tue, 03 Oct 2023   Prob (F-statistic):              0.661
Time:                        23:30:26   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust       

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
