In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


data = pd.read_csv('../datasources/Wine.csv')
X = data.iloc[:, 0:13].values
y = data.iloc[:, 13].values

#Training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Principal Component Analysis
from sklearn.decomposition import PCA
principalComponentAnalysis = PCA(n_components = 2)

X_train2 = principalComponentAnalysis.fit_transform(X_train)
X_test2 = principalComponentAnalysis.transform(X_test)

#Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)


classifier2 = LogisticRegression(random_state=0)
classifier2.fit(X_train2,y_train)

#predictions
y_pred = classifier.predict(X_test)
y_pred2 = classifier2.predict(X_test2)

from sklearn.metrics import confusion_matrix

print('reel / without PCA')
cm = confusion_matrix(y_test,y_pred)
print(cm)


print("reel / with PCA" )
cm2 = confusion_matrix(y_test,y_pred2)
print(cm2)


print('with PCA and without PCA')
cm3 = confusion_matrix(y_pred,y_pred2)
print(cm3)




reel / without PCA
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
reel / with PCA
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
with PCA and without PCA
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
