In [12]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data=pd.read_excel('../datasources/iris.xlsx')
#print(data)

x=data.iloc[:,1:4].values #non-linear variables
y=data.iloc[:,4:].values  #linear variables
y = y.ravel()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

from sklearn.preprocessing import StandardScaler

standardScaler=StandardScaler()
X_train=standardScaler.fit_transform(x_train)
X_test=standardScaler.transform(x_test)

#Logistic
from sklearn.linear_model import LogisticRegression
logisticRegression=LogisticRegression(random_state=0)
logisticRegression.fit(X_train,y_train)

y_prediction=logisticRegression.predict(X_test)


from sklearn.metrics import confusion_matrix
confusionMatrix=confusion_matrix(y_test,y_prediction)
print('LogisticRegression')
print(confusionMatrix)

#KNN
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=1,metric='minkowski')
knn.fit(X_train,y_train)

y_prediction=knn.predict(X_test)
confusionMatrix=confusion_matrix(y_test,y_prediction)
print('KNN')
print(confusionMatrix)

#Support Vector Machine 
from sklearn.svm import SVC
supportVectorClassification=SVC(kernel='poly')
supportVectorClassification.fit(X_train,y_train)
y_prediction=supportVectorClassification.predict(X_test)
confusionMatrix=confusion_matrix(y_test,y_prediction)
print('SVC')
print(confusionMatrix)

#G. Naive Bayes
from sklearn.naive_bayes import GaussianNB
gaussianNaiveBayes=GaussianNB()
gaussianNaiveBayes.fit(X_train,y_train)
y_prediction=gaussianNaiveBayes.predict(X_test)

confusionMatrix=confusion_matrix(y_test,y_prediction)
print(gaussianNaiveBayes)
print(confusionMatrix)

#Decision Tree
from sklearn.tree import DecisionTreeClassifier
decisionTreeclassifier=DecisionTreeClassifier(criterion='entropy')

decisionTreeclassifier.fit(X_train,y_train)
y_prediction=decisionTreeclassifier.predict(X_test)

confusionMatrix=confusion_matrix(y_test,y_prediction)
print('DecisionTreeClassifier')
print(confusionMatrix)

#Random Forest
from sklearn.ensemble import RandomForestClassifier
randomForestClassifier=RandomForestClassifier(n_estimators=10, criterion= 'entropy')
randomForestClassifier.fit(X_train,y_train)

y_prediction=randomForestClassifier.predict(X_test)
confusionMatrix=confusion_matrix(y_test,y_prediction)
print('RandomForestClassifier')
print(confusionMatrix) 

#ROC,TPR,FPR values
y_probability=randomForestClassifier.predict_proba(X_test)
#print(y_test)
#print(y_probability[:,0])

from sklearn import metrics
fpr, tpr, threshold=metrics.roc_curve(y_test,y_probability[:,0],pos_label='e')
#print(fpr)
#print(tpr)


LogisticRegression
[[16  0  0]
 [ 0 18  1]
 [ 0  2 13]]
KNN
[[16  0  0]
 [ 0 18  1]
 [ 0  2 13]]
SVC
[[16  0  0]
 [ 0 19  0]
 [ 0  4 11]]
GaussianNB()
[[16  0  0]
 [ 0 19  0]
 [ 0  2 13]]
DecisionTreeClassifier
[[16  0  0]
 [ 0 18  1]
 [ 0  1 14]]
RandomForestClassifier
[[16  0  0]
 [ 0 18  1]
 [ 0  2 13]]


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_ranking.py:1133: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
