In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data=pd.read_csv('../datasources/veriler.csv')
#print(data)

x=data.iloc[:,1:4].values #non-linear variables
y=data.iloc[:,4:].values  #linear variables
y = y.ravel()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

from sklearn.preprocessing import StandardScaler

standardScaler=StandardScaler()
X_train=standardScaler.fit_transform(x_train)
X_test=standardScaler.transform(x_test)

from sklearn.linear_model import LogisticRegression
logisticRegression=LogisticRegression(random_state=0)
logisticRegression.fit(X_train,y_train)

y_prediction=logisticRegression.predict(X_test)
print(y_prediction)

print(y_test)

from sklearn.metrics import confusion_matrix
confusionMatrix=confusion_matrix(y_test,y_prediction)
print(confusionMatrix)

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=1,metric='minkowski')
knn.fit(X_train,y_train)

y_prediction=knn.predict(X_test)
confusionMatrix=confusion_matrix(y_test,y_prediction)
print(confusionMatrix)

from sklearn.svm import SVC
supportVectorClassification=SVC(kernel='rbf')
supportVectorClassification.fit(X_train,y_train)
y_prediction=supportVectorClassification.predict(X_test)
confusionMatrix=confusion_matrix(y_test,y_prediction)
print('SVC')
print(confusionMatrix)

from sklearn.naive_bayes import GaussianNB
gaussianNaiveBayes=GaussianNB()
gaussianNaiveBayes.fit(X_train,y_train)
y_prediction=gaussianNaiveBayes.predict(X_test)

confusionMatrix=confusion_matrix(y_test,y_prediction)
print(gaussianNaiveBayes)
print(confusionMatrix)

from sklearn.tree import DecisionTreeClassifier
decisionTreeclassifier=DecisionTreeClassifier(criterion='entropy')

decisionTreeclassifier.fit(X_train,y_train)
y_prediction=decisionTreeclassifier.predict(X_test)

confusionMatrix=confusion_matrix(y_test,y_prediction)
print('DecisionTreeClassifier')
print(confusionMatrix)
##
from sklearn.ensemble import RandomForestClassifier
randomForestClassifier=RandomForestClassifier(n_estimators=10, criterion= 'entropy')
randomForestClassifier.fit(X_train,y_train)

y_prediction=randomForestClassifier.predict(X_test)
confusionMatrix=confusion_matrix(y_test,y_prediction)
print('RandomForestClassifier')
print(confusionMatrix) 


['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
[[0 1]
 [7 0]]
[[1 0]
 [1 6]]
SVC
[[1 0]
 [5 2]]
GaussianNB()
[[0 1]
 [6 1]]
DecisionTreeClassifier
[[1 0]
 [1 6]]
RandomForestClassifier
[[1 0]
 [3 4]]
